In [4]:
import numpy as np
import random

# Definimos las matrices para las vocales
a = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1])

e = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1])

i = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1])

o = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1, 
              1, 1, 1, 1, 1, 1, 1, 1])

u = np.array([1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, 1, 1, 1, 1, 1, 1, 1])

vocales = [a, e, i, o, u]

# Inicializamos la matriz de pesos W con ceros
W = np.zeros((64, 64))

# Entrenamiento
for vocal in vocales:
    vocal_flat = vocal.reshape(64)
    W += np.outer(vocal_flat, vocal_flat)

print("Matriz de pesos después de entrenar:")
print(W)

# Función para agregar ruido al patrón
def agregar_ruido(patron, porcentaje_ruido):
    patron_ruidoso = patron.copy()
    num_bits_a_alterar = int(len(patron_ruidoso) * porcentaje_ruido)
    indices = random.sample(range(len(patron_ruidoso)), num_bits_a_alterar)
    for i in indices:
        patron_ruidoso[i] = 1 if patron_ruidoso[i] == 0 else 0
    return patron_ruidoso

# Función de activación de la red (recuperación)
def actualizar_patron(patron):
    nuevo_patron = np.dot(W, patron)
    nuevo_patron = np.where(nuevo_patron >= 0, 1, -1)
    return nuevo_patron

# Prueba de recuperación
def evaluar_recuperacion(vocal_original):
    vocal_ruidosa = agregar_ruido(vocal_original, 0.2)
    patron = vocal_ruidosa
    print("Patrón inicial ruidoso:")
    print(patron.reshape(8, 8))
    
    # Iteración para intentar recuperar el patrón
    for _ in range(10):  # 10 iteraciones de recuperación
        patron = actualizar_patron(patron)
    
    print("Patrón final después de recuperación:")
    print(patron.reshape(8, 8))
    
    if np.array_equal(patron, vocal_original):
        print("Recuperación exitosa.")
    else:
        print("No se pudo recuperar completamente el patrón.")

# Evaluación para cada vocal
for idx, vocal in enumerate(vocales):
    print(f"\nEvaluando recuperación de la vocal {['A', 'E', 'I', 'O', 'U'][idx]}")
    evaluar_recuperacion(vocal.reshape(64))


Matriz de pesos después de entrenar:
[[5. 3. 3. ... 3. 3. 5.]
 [3. 5. 5. ... 1. 1. 3.]
 [3. 5. 5. ... 1. 1. 3.]
 ...
 [3. 1. 1. ... 5. 5. 3.]
 [3. 1. 1. ... 5. 5. 3.]
 [5. 3. 3. ... 3. 3. 5.]]

Evaluando recuperación de la vocal A
Patrón inicial ruidoso:
[[ 1  1  1  0  1  1  1  1]
 [ 0  0  0 -1 -1 -1 -1  1]
 [ 1  0 -1 -1 -1 -1  0  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  0  0  1  0  1]
 [ 1 -1  0 -1 -1 -1 -1  1]
 [ 1  0 -1 -1 -1 -1 -1  0]
 [ 1 -1 -1 -1 -1 -1 -1  1]]
Patrón final después de recuperación:
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  1  1  1  1  1]]
No se pudo recuperar completamente el patrón.

Evaluando recuperación de la vocal E
Patrón inicial ruidoso:
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1  0 -1 -1 -1 -1 -1]
 [ 0 -1  0  0 -1  0 -1 -1]
 [ 0  1  1  1  1  0  1  1]
 [ 1  1  0  1  1  1  1  0]
 [ 1 -1 -1  0 -1 -1 -1 -1]
 [ 