Red de Hopfield
Redes Neuronales y Aprendizaje Profundo
Rodrigo F. Román Godínez
Flores Lara Alberto
5BV1

Objetivo:
1. Implementar una red de Hopfield que almacene y recupere caracteres (por ejemplo, letras o números representados en una matriz binaria de 0s y 1s).
2. Determinar la capacidad de la red de Hopfield: ¿Cuántos caracteres puede almacenar y recuperar correctamente sin error?
3. Comparar el desempeño de la red de Hopfield con una memoria asociativa Hebbiana en términos de capacidad de almacenamiento, recuperación y robustez frente a entradas ruidosas.

Instrucciones:
1. Parte 1: Programación de la Red de Hopfield
* Paso 1: Crea una función que implemente la red de Hopfield, utilizando la regla de actualización de pesos. Utiliza una matriz de 8x8 para representar cada carácter.

In [61]:
import numpy as np

# Inicialización de la matriz de pesos W con ceros
def inicializar_pesos(dimension):
    return np.zeros((dimension, dimension))

# Regla de actualización de pesos
def entrenar_red_hopfield(W, patrones):
    for patron in patrones:
        patron = patron.reshape(-1)
        W += np.outer(patron, patron)
    np.fill_diagonal(W, 0)
    return W


Paso 2: Entrena la red de Hopfield con un conjunto de caracteres en formato binario. Los patrones de entrenamiento deben ser vectores de 64 elementos.

In [62]:
# Definir patrones de entrenamiento
a = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1])

e = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, -1, -1, -1, -1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1])

i = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              -1, -1, -1, 1, 1, -1, -1, -1,
              1, 1, 1, 1, 1, 1, 1, 1])

o = np.array([1, 1, 1, 1, 1, 1, 1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1, 
              1, 1, 1, 1, 1, 1, 1, 1])

u = np.array([1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, -1, -1, -1, -1, -1, -1, 1,
              1, 1, 1, 1, 1, 1, 1, 1])

patrones = [a, e, i, o, u]

# Se inicializa W y entrena
W = inicializar_pesos(64)
W = entrenar_red_hopfield(W, patrones)


Paso 3: Implementa una función para recuperar un carácter dado un patrón ruidoso o incompleto como entrada. La red debe converger a uno de los
patrones almacenados.

In [63]:
# Función de activación para actualizar el patrón
def actualizar_patron(W, patron):
    nuevo_patron = np.dot(W, patron)
    return np.where(nuevo_patron >= 0, 1, -1)

# Función para recuperar un carácter a partir de un patrón ruidoso
def recuperar_caracter(W, patron_ruidoso, iteraciones=1):
    patron = patron_ruidoso
    for _ in range(iteraciones):
        patron = actualizar_patron(W, patron)
    return patron


Paso 4: Evalúa cuántos caracteres diferentes la red puede almacenar y recuperar adecuadamente. Para esto, presenta patrones ruidosos o
incompletos a la red y mide si la red puede converger al carácter almacenado correspondiente.

In [64]:
# Función para agregar ruido
def agregar_ruido(patron, porcentaje_ruido):
    patron_ruidoso = patron.copy()
    num_bits_a_alterar = int(len(patron_ruidoso) * porcentaje_ruido)
    indices = np.random.choice(len(patron_ruidoso), num_bits_a_alterar, replace=False)
    for i in indices:
        patron_ruidoso[i] *= -1
    return patron_ruidoso

# Evaluación de recuperación
def evaluar_recuperacion(W, patrones, ruido=0.2):
    for idx, patron in enumerate(patrones):
        print(f"Evaluando recuperación del patrón {idx + 1}")
        #patron_ruidoso = agregar_ruido(patron, ruido)
        patron_ruidoso=patron
        recuperado = recuperar_caracter(W, patron_ruidoso)
        
        print(recuperado.reshape(8,8))
        
        if np.array_equal(recuperado, patron):
            print("Recuperación exitosa.")
        else:
            print("Recuperación fallida.")


In [65]:
# Inicializamos y entrenamos la red de Hopfield
W = inicializar_pesos(64)
W = entrenar_red_hopfield(W, patrones)

# Evaluamos la recuperación de cada patrón con ruido
evaluar_recuperacion(W, patrones, ruido=0.2)

Evaluando recuperación del patrón 1
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  1  1  1  1  1]]
Recuperación fallida.
Evaluando recuperación del patrón 2
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1  1  1  1  1  1  1  1]]
Recuperación fallida.
Evaluando recuperación del patrón 3
[[ 1  1  1  1  1  1  1  1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [-1 -1 -1  1  1 -1 -1 -1]
 [ 1  1  1  1  1  1  1  1]]
Recuperación exitosa.
Evaluando recuperación del patrón 4
[[ 1  1  1  1  1  1  1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1 -1 -1 -1 -1 -1 -1  1]
 [ 1


Conclusión

En la práctica de comparación entre la red de Hopfield y la memoria asociativa, se observaron resultados similares en ambas aproximaciones en cuanto a la recuperación de patrones. Aunque se ajustaron los niveles de ruido, tanto aumentándolos como reduciéndolos, los resultados no mostraron una mejora significativa en la capacidad de recuperación.

Específicamente, de los patrones de letras entrenados, solo se logró recuperar consistentemente las letras "I" y "O", mientras que los demás patrones no convergieron al carácter original deseado. Esto indica que ambas redes, en este caso, tienen limitaciones en su capacidad de almacenamiento y recuperación.

Estos resultados sugieren que, aunque la red de Hopfield y la memoria asociativa pueden recuperar patrones en escenarios con poca variación, su efectividad disminuye cuando se enfrentan a datos ruidosos o con mayor número de patrones.